project:
  type: website

website:
  title: "Roy Mwavita"
  google-analytics: "G-XNMP9FSHZH"
  search: false
  description: "Data analytics, dashboards, and monitoring & evaluation portfolio"
  open-graph: true
  twitter-card: true
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2026, Roy Mwavita. Built with Quarto." 

  navbar:
    right:
      - href: index.qmd
        text: About Me
        
      - href: projects.qmd
        text: Projects

      - href: dashboards.qmd
        text: Dashboards

      - href: digest.qmd
        text: R Toolkit Digest
        
      - href: newsletter.qmd
        text: Newsletter

        

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">